name: Dev-Push

on:
  push:
    branches: [ dev ]
    
  workflow_dispatch:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.SERVER }}-app  # Declare app_name as an environment variable
      APP_PATH: /home/ubuntu/app/${{ secrets.SERVER }}-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/*,ecosystem.config.js,package.json,README.md"
          target: "${{ env.APP_PATH }}"  # Change this to your app's path

      - name: Install dependencies on server and Run Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 

            echo "Check Node Version"
            node -v

            echo "Check NPM Version"
            npm -v

            #Move to App Directory
            cd ${{ env.APP_PATH }}

            #Install app dependencies
            npm install

            #Delete All Logs
            pm2 flush all

            #Start App
            cross-env ROOTPOINT=${{ secrets.ROOT_SERVER }} SERVER=${{ secrets.SERVER }} ENVIRONMENT=development pm2 restart ecosystem.config.js
            
            #Save App Service
            pm2 save