name: Nevil-Dev-Push

on:
  push:
    branches: [nevil-dev]

  workflow_dispatch:
    branches: [nevil-dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/